import Lddec

lista = Lddec.Lddec()

lista.inserir_fim("G")
lista.inserir_fim("A")
lista.inserir_fim("B")
lista.inserir_fim("R")
lista.inserir_fim("I")
lista.inserir_fim("E")
lista.inserir_fim("L")
lista.show()
lista.ver_quantidade()
lista.ver_primeiro()
lista.ver_ultimo()
print()

print("Removendo todos apos o B, espera-se: G A B")
lista.remover_todos_apos("B")
lista.show()
lista.ver_quantidade()
lista.ver_primeiro()
lista.ver_ultimo()
print()

print("Adicionando o H, espera-se: G A B H")
lista.inserir_fim("H")
lista.show()
lista.ver_quantidade()
lista.ver_primeiro()
lista.ver_ultimo()
print()

print("Removendo todos apos o B, espera-se: G A B")
lista.remover_todos_apos("B")
lista.show()
lista.ver_quantidade()
lista.ver_primeiro()
lista.ver_ultimo()
print()

